In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_excel("../../data/raw/Global_Peace_Index.xlsx", sheet_name="Overall Scores", header=5)

In [ ]:
# Filter out csv so we only have score related columns
score_columns = [col for col in df.columns if 'Score' in str(col)]
df_scores_only = df[['country'] + score_columns]

In [17]:
df_scores_only

,country,2008_Score,2009_Score,2010_Score,2011_Score,2012_Score,2013_Score,2014_Score,2015_Score,2016_Score,2017_Score,2018_Score,2019_Score,2020_Score,2021_Score,2022_Score,2023_Score,2024_Score
0,Afghanistan,3.218,3.296,3.201,3.212,3.265,3.293,3.272,3.363,3.457,3.552,3.614,3.619,3.657,3.663,3.620,3.287,3.294
1,Albania,1.840,1.859,1.850,1.873,1.922,1.944,1.944,1.888,1.851,1.820,1.808,1.742,1.809,1.796,1.786,1.795,1.809
2,Algeria,2.269,2.251,2.293,2.345,2.307,2.253,2.227,2.169,2.192,2.186,2.193,2.195,2.143,2.174,2.068,2.102,2.110
3,Angola,2.124,2.042,2.124,2.113,2.068,2.105,2.122,1.975,2.036,2.024,2.012,1.973,2.008,2.010,1.979,2.119,2.043
4,Argentina,1.918,1.984,2.010,1.950,1.892,2.051,1.957,2.056,2.068,2.025,1.997,2.010,1.970,1.961,1.948,1.857,1.855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,Venezuela,2.457,2.524,2.613,2.555,2.473,2.509,2.569,2.676,2.770,2.786,2.788,2.838,2.832,2.833,2.881,2.843,2.821
159,Vietnam,1.825,1.825,1.844,1.892,1.931,1.895,1.851,1.937,1.896,1.921,1.944,1.925,1.955,1.883,1.815,1.745,1.802
160,Yemen,2.421,2.536,2.585,2.604,2.682,2.616,2.587,2.841,3.276,3.182,3.189,3.384,3.406,3.515,3.595,3.322,3.397
161,Zambia,2.022,1.972,1.892,1.782,1.868,1.782,1.873,1.870,1.817,1.855,1.838,1.835,1.813,2.031,1.940,1.954,1.948
162,Zimbabwe,2.461,2.742,2.487,2.467,2.397,2.373,2.356,2.203,2.266,2.280,2.298,2.418,2.403,2.352,2.361,2.353,2.396

In [18]:
df_scores_only.to_csv("../../data/processed/Global_Peace_Index_Processed.csv", index=False)